---
- name: azure-test
  hosts: 127.0.0.1 
  connection: local
  tasks: 
  - name: "Azure VM"
    azure_rm_virtualmachine:
      resource_group: test-ram-today
      name: testvm10
      os_type: Linux
      ssh_public_keys: ram.pub
      admin_username: rchittala
      image:
        offer: RHEL
        sku: '7-RAW'
        version: latest
